<?php

	$y=0;
	$apps[$x]['menu'][$y]['title']['en-us'] = "Provision Editor";
	$apps[$x]['menu'][$y]['title']['ar-eg'] = "محرر";
	$apps[$x]['menu'][$y]['title']['de-at'] = "Bereitstellungs Editor";
	$apps[$x]['menu'][$y]['title']['de-ch'] = "Beschreibung";
	$apps[$x]['menu'][$y]['title']['de-de'] = "Bereitstellungs Editor";
	$apps[$x]['menu'][$y]['title']['es-cl'] = "Editor de Provisionamiento";
	$apps[$x]['menu'][$y]['title']['es-mx'] = "Redacción";
	$apps[$x]['menu'][$y]['title']['fr-ca'] = "Rédacteur";
	$apps[$x]['menu'][$y]['title']['fr-fr'] = "Editeur de Provisioning";
	$apps[$x]['menu'][$y]['title']['he-il'] = "עורך Provision";
	$apps[$x]['menu'][$y]['title']['it-it'] = "Editor di Provisioning";
	$apps[$x]['menu'][$y]['title']['nl-nl'] = "Voorzieningen bewerker";
	$apps[$x]['menu'][$y]['title']['pl-pl'] = "Oficjalna strona";
	$apps[$x]['menu'][$y]['title']['pt-br'] = "Editor de Provisão";
	$apps[$x]['menu'][$y]['title']['pt-pt'] = "Editor de Provisionamento";
	$apps[$x]['menu'][$y]['title']['ro-ro'] = "Editor de provizii";
	$apps[$x]['menu'][$y]['title']['ru-ru'] = "Редактор шаблонов автоконфигурации";
	$apps[$x]['menu'][$y]['title']['sv-se'] = "Provision Editor";
	$apps[$x]['menu'][$y]['title']['uk-ua'] = "Редактор даних";
	$apps[$x]['menu'][$y]['title']['zh-cn'] = "规定编辑器";
	$apps[$x]['menu'][$y]['title']['ja-jp'] = "プロビジョニングエディター";
	$apps[$x]['menu'][$y]['title']['ko-kr'] = "프로비저닝 편집자";
	$apps[$x]['menu'][$y]['uuid'] = "57773542-a565-1a29-605d-6535da1a0870";
	$apps[$x]['menu'][$y]['parent_uuid'] = "594d99c5-6128-9c88-ca35-4b33392cec0f";
	$apps[$x]['menu'][$y]['category'] = "external";
	$apps[$x]['menu'][$y]['path'] = "/app/edit/index.php?dir=provision";
	$apps[$x]['menu'][$y]['groups'][] = "superadmin";
	$y++;
